version: '3'

networks:
    localdev:

volumes:
    db:

services:
    postgres:
        image: postgres:15
        container_name: database2-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: database2
            POSTGRES_USER: database2
            POSTGRES_PASSWORD: database2
        volumes:
            - db:/var/lib/postgresql/data/
            - ./:/app
        networks:
            - localdev
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "database2"]
            interval: 1s
            timeout: 3s
            retries: 30

    django:
        container_name: database2-django
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
              DEV_MODE: 1
              DATABASE_URL: postgres://database2:database2@postgres/database2
        ports:
            - "8000:8000"
        volumes:
            - .:/home/database2
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            DATABASE_URL: postgres://database2:database2@postgres/database2
            PORT: 8000
        networks:
            - localdev
