# Generated by Django 4.2.6 on 2023-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pitcher', models.CharField(max_length=50)),
                ('pitch_count', models.PositiveIntegerField()),
                ('pitch_type', models.CharField(max_length=50)),
                ('velo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
