# Generated by Django 4.2.7 on 2023-11-20 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0002_pitchingdata_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FB", "Fastball"),
                            ("CB", "Curveball"),
                            ("CH", "Changeup"),
                            ("SL", "Slider"),
                            ("SP", "Splitter"),
                            ("CU", "Cutter"),
                            ("KN", "Knuck"),
                            ("EE", "Eephus"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("BL", "Ball"),
                            ("XL", "Strike Looking"),
                            ("XS", "Strike Swinging"),
                            ("FB", "Foul Ball"),
                            ("BO", "BIP Out"),
                            ("SGL", "Single"),
                            ("DBL", "Double"),
                            ("TPL", "Triple"),
                            ("HR", "HR"),
                            ("HBP", "HBP"),
                            ("D3S", "Drop 3d & Safe"),
                            ("ROE", "Reach on Error"),
                        ],
                        max_length=100,
                    ),
                ),
                ("velo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="dataentry.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pitcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PitchingData",
        ),
        migrations.AddField(
            model_name="pitcher",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pitchers",
                to="dataentry.team",
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="pitcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pitches",
                to="dataentry.pitcher",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="dataentry.team",
            ),
        ),
    ]
