# Generated by Django 4.2.7 on 2023-11-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0003_game_pitch_pitcher_team_delete_pitchingdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dataentry.team",
            ),
            preserve_default=False,
        ),
    ]
