# Generated by Django 4.2.7 on 2023-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0004_pitch_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="pitch_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
