# Generated by Django 4.2.7 on 2023-11-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitchers', to='dataentry.team')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pitch_type', models.CharField(choices=[('FB', 'Fastball'), ('CB', 'Curveball'), ('CH', 'Changeup'), ('SL', 'Slider'), ('SPL', 'Splitter'), ('CUT', 'Cutter'), ('KN', 'Knuck'), ('EE', 'Eephus')], max_length=5)),
                ('result', models.CharField(choices=[('BALL', 'Ball'), ('K Looking', 'Strike Looking'), ('K Swinging', 'Strike Swinging'), ('Foul Ball', 'Foul Ball'), ('BIP OUT', 'BIP Out'), ('SGL', 'Single'), ('DBL', 'Double'), ('TPL', 'Triple'), ('HR', 'HR'), ('HBP', 'HBP'), ('D3S', 'Drop 3d & Safe'), ('ROE', 'Reach on Error')], max_length=100)),
                ('pitch_count', models.IntegerField()),
                ('velo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='dataentry.pitcher')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='dataentry.team')),
            ],
        ),
    ]
